spring:
  profiles:
    active:
    - local
    
---


spring:
  profiles:  - local
  
  mvc:
    view:
      prefix: "/WEB-INF/views"
      suffix: ".jsp"

  datasource:
    url: jdbc:mysql://localhost:3306/pizza?characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  session:
    jdbc:
      initialize-schema: always
      
server:
  port: 8080
  tomcat:    file-encoding: UTF-8
    
  servlet:    encoding:      charset: UTF-8
      enabled: true
      force: true
      
    jsp:
      init-parameters:        development: true
    session:      timeout: 7200
  error:    whitelabel:      enabled: false
      
mybatis:  type-aliases-package: com.pizza_a.example.domain
  mapper-locations: mapper/**/*.xml
  configuration:
    cache-enabled: false
    local-cache-scope: statement
logging:
  config: classpath:logback-spring.xml